services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "git config --global --add safe.directory /srv/jekyll &&
             bundle install --jobs 4 --retry 3 &&
             bundle exec jekyll serve --watch --force_polling --livereload --host 0.0.0.0"
    environment:
      BUNDLE_PATH: /usr/local/bundle
      BUNDLE_BIN: /usr/local/bundle/bin
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - jekyll-bundle:/usr/local/bundle

volumes:
  jekyll-bundle:
